spring:
  application:
    name: user-api
  datasource:
    url: jdbc:h2:mem:users
    username: root
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
  profiles:
    active: test
server:
  port: 8000
